let products = [
  {
    id: 1001,
    title: "Art",
    location: "Nahda",
    space: 10,
    price: 200,
    image: "images/art.png",
    rating: 4,
    displaySpace: 10,
  },
  {
    id: 1002,
    title: "Basket Ball",
    location: "Oud Metha",
    space: 10,
    price: 245,
    image: "images/basket_ball.png",
    rating: 5,
    displaySpace: 10,
  },
  {
    id: 1003,
    title: "Coding",
    location: "Barsha",
    space: 10,
    price: 220,
    image: "images/coding.png",
    rating: 5,
    displaySpace: 10,
  },
  {
    id: 1004,
    title: "Cricket",
    location: "Qusais",
    space: 10,
    price: 275,
    image: "images/cricket.png",
    rating: 3,
    displaySpace: 10,
  },
  {
    id: 1005,
    title: "Dancing",
    location: "Sufouh",
    space: 10,
    price: 265,
    image: "images/dancing.png",
    rating: 4,
    displaySpace: 10,
  },
  {
    id: 1006,
    title: "Foot Ball",
    location: "Al Quoz",
    space: 10,
    price: 255,
    image: "images/foot_ball.png",
    rating: 5,
    displaySpace: 10,
  },
  {
    id: 1007,
    title: "Karate",
    location: "Greens",
    space: 10,
    price: 240,
    image: "images/karate.png",
    rating: 3,
    displaySpace: 10,
  },
  {
    id: 1008,
    title: "Music",
    location: "Meadows",
    space: 10,
    price: 235,
    image: "images/music.png",
    rating: 3,
    displaySpace: 10,
  },
  {
    id: 1009,
    title: "Swimming",
    location: "Muhaisnah",
    space: 10,
    price: 270,
    image: "images/swimming.png",
    rating: 4,
    displaySpace: 10,
  },
  {
    id: 1010,
    title: "Table Tennis",
    location: "Jumeirah",
    space: 10,
    price: 230,
    image: "images/table_tennis.png",
    rating: 3,
    displaySpace: 10,
  },
];
